name: Go Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      id: setup-go
      with:
        go-version: 'stable'

    - name: Download Go modules
      if: ${{ steps.setup-go.outputs.cache-hit != 'true' }}
      run: go mod download

    - name: Run tests
      run: go test ./...
